//! foF2 and foE: where the F2 and E layers get their peak densities.
//!
//! The F2 layer used to be one scalar for the whole domain, derived from the
//! sunspot number and nothing else. That is what made coverage contours snap to
//! grid cells and left the terminator with no effect on F2 at all. This module
//! replaces it with a horizontally varying source, and keeps the old scalar as
//! an explicit, selectable fallback rather than deleting it.
//!
//! # Two backends, both surfaced
//!
//! * [`Fof2Backend::ConstantSsn`] - [`fof2_from_ssn`] everywhere. The previous
//!   behaviour, bit for bit.
//! * [`Fof2Backend::Gridded`] - the bundled climatology grid, sampled at each
//!   point's own latitude and local solar time.
//!
//! Whichever ran is written into `Assumptions::fof2_source` verbatim, including
//! when the grid failed to load and the constant took over.
//!
//! # Provenance of the bundled grid - READ THIS
//!
//! `assets/fof2_grid.tsv` is laid out the way the operational maps are (a
//! latitude x local-solar-time table per season, tabulated at two solar-activity
//! levels and interpolated in NmF2 between them - the CCIR/URSI idiom), but the
//! NUMBERS IN IT ARE NOT CCIR, URSI OR IRI DATA. Those coefficient sets are not
//! in this repository and are not fetched at runtime. The bundled table is
//! generated by `src/bin/gen_fof2_grid.rs` from [`climatology_fof2`] below,
//! which is an ORDER-OF-MAGNITUDE CLIMATOLOGY OF MY OWN CONSTRUCTION: its
//! SHAPE follows the published behaviour of foF2 (afternoon diurnal maximum,
//! equatorial-anomaly crests either side of the magnetic equator, high-latitude
//! trough, winter anomaly in daytime midlatitudes) but its ABSOLUTE ANCHORS are
//! calibrated only to [`fof2_from_ssn`], the same coarse midlatitude anchor the
//! scalar model already used.
//!
//! Treat foF2 MAGNITUDES as indicative. The defensible part is that foF2 now
//! VARIES - with latitude, with local time, with season - so the terminator,
//! the equatorial anomaly and the day/night asymmetry exist at all. Dropping a
//! real IRI or CCIR table into the same file layout is a file replacement, not
//! a code change.

use std::f64::consts::PI;
use std::sync::OnceLock;

use skipzone::density::density_at_critical_frequency;
use skipzone::units::Hertz;

use crate::chapman::{PeakDensitySource, PeakSample};
use crate::solar::Season;

/// foF2 [MHz] derived from sunspot number alone. The peak plasma density NmF2
/// (and hence foF2^2, since NmF2 is proportional to foF2^2) is taken linear in
/// SSN - the standard first-order statement that peak ionisation scales with
/// solar activity - calibrated to representative midlatitude anchors:
/// foF2 ~ 4.5 MHz at SSN 0 and ~10 MHz at SSN 150.
///
/// This is a coarse climatological anchor, NOT a path-, season-, or
/// time-specific prediction, and it is always surfaced in the UI. There is
/// deliberately no hidden day/night branch: SSN is the only driver, so an
/// operator who selects this backend sees exactly the foF2 the engine is given.
///
/// It is also the calibration point of the gridded backend: [`climatology_fof2`]
/// reduces to exactly this value at the reference latitude, equinox, and the
/// diurnal maximum, so switching backends cannot silently move the anchor.
#[must_use]
pub fn fof2_from_ssn(ssn: f64) -> f64 {
    // foF2(0)^2 = 4.5^2 = 20.25; slope (10^2 - 20.25)/150 = 0.5317.
    (20.25 + 0.531_666_7 * ssn.max(0.0)).sqrt()
}

/// Which foF2 model builds the F2 layer.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Fof2Backend {
    /// [`fof2_from_ssn`], one value for the whole domain.
    ConstantSsn,
    /// The bundled climatology grid, varying with latitude and local solar time.
    Gridded,
}

impl Fof2Backend {
    pub const ALL: [Self; 2] = [Self::Gridded, Self::ConstantSsn];

    #[must_use]
    pub fn label(self) -> &'static str {
        match self {
            Self::ConstantSsn => "constant (SSN only)",
            Self::Gridded => "gridded climatology (lat / local time / season)",
        }
    }
}

// --- The climatology the bundled grid is generated from -------------------
//
// Every constant below is an ORDER-OF-MAGNITUDE ANCHOR chosen to reproduce a
// documented qualitative behaviour, not a fitted coefficient. They are all
// listed here rather than buried in the function so that what the model claims
// is inspectable in one place.

/// Latitude the [`fof2_from_ssn`] anchor is taken to describe, degrees. The
/// climatology reduces to that anchor here, at equinox, at the diurnal peak.
pub const REFERENCE_LAT_DEG: f64 = 45.0;
/// Local solar time of the diurnal maximum, hours. Afternoon, not noon:
/// the F2 peak lags local noon by a couple of hours.
pub const DIURNAL_PEAK_LST_H: f64 = 14.0;
/// Trough-to-peak ratio of the diurnal cycle at midlatitudes: night foF2 is
/// about half the afternoon value at moderate solar activity.
pub const DIURNAL_MIN_FRACTION: f64 = 0.50;
/// Magnetic-dip latitude of the equatorial-anomaly crests, degrees.
pub const ANOMALY_CREST_LAT_DEG: f64 = 16.0;
/// Half-width of a crest, degrees.
pub const ANOMALY_CREST_WIDTH_DEG: f64 = 12.0;
/// Crest enhancement over the midlatitude value at its afternoon maximum.
pub const ANOMALY_CREST_GAIN: f64 = 0.55;
/// Latitude the high-latitude trough is centred on, degrees.
pub const POLAR_TROUGH_LAT_DEG: f64 = 62.0;
/// Width of the trough's transition, degrees.
pub const POLAR_TROUGH_WIDTH_DEG: f64 = 7.0;
/// Depth of the trough as a fraction of the midlatitude value, at night.
pub const POLAR_TROUGH_DEPTH: f64 = 0.45;
/// How much of that depth survives in full daylight. The main ionospheric
/// trough is predominantly a NIGHT-TIME feature; applying its full depth to the
/// sunlit high-latitude ionosphere would depress daytime high-latitude foF2 far
/// below what is observed, and would (measurably) close high-band paths over
/// the pole that are in fact open.
pub const POLAR_TROUGH_DAY_FRACTION: f64 = 0.35;
/// Daytime winter-anomaly enhancement (winter day exceeds summer day at
/// midlatitudes - the classic anomaly, driven by the O/N2 ratio, not by
/// insolation).
pub const WINTER_DAY_GAIN: f64 = 0.18;
/// Night-time winter depression.
pub const WINTER_NIGHT_LOSS: f64 = 0.22;
/// Daytime summer depression.
pub const SUMMER_DAY_LOSS: f64 = 0.14;
/// Night-time summer enhancement.
pub const SUMMER_NIGHT_GAIN: f64 = 0.22;
/// Latitude at which the seasonal terms reach full strength, degrees; they
/// taper to nothing at the equator.
pub const SEASON_FULL_LAT_DEG: f64 = 40.0;
/// Soft floor on foF2, MHz, applied as `sqrt(f^2 + f_min^2)` so it stays smooth.
/// The night F region never vanishes; without a floor the model would let it.
pub const FOF2_FLOOR_MHZ: f64 = 1.6;

/// How "daytime" a local solar time is, 0 at 03 LST to 1 at 15 LST. Used to
/// weight the terms that only act in daylight (the anomaly crests) and to blend
/// the day and night halves of the seasonal terms.
fn day_weight(lst_h: f64) -> f64 {
    0.5 * (1.0 + (2.0 * PI * (lst_h - 15.0) / 24.0).cos())
}

/// foF2 [MHz] from the bundled climatology, evaluated directly rather than
/// through the grid. This is the function `src/bin/gen_fof2_grid.rs` tabulates;
/// see the module docs for exactly how much it is worth.
///
/// `season` is the LOCAL season (already hemisphere-flipped); `lst_h` is local
/// solar time in hours.
#[must_use]
pub fn climatology_fof2(lat_deg: f64, lst_h: f64, season: Season, ssn: f64) -> f64 {
    let reference = fof2_from_ssn(ssn);

    // Diurnal: one harmonic peaking at DIURNAL_PEAK_LST_H. A single harmonic
    // understates the sharpness of the post-sunrise rise; it is kept because a
    // second harmonic would imply a precision the anchors do not have.
    let mid = 0.5 * (1.0 + DIURNAL_MIN_FRACTION);
    let amp = 0.5 * (1.0 - DIURNAL_MIN_FRACTION);
    let diurnal = mid + amp * (2.0 * PI * (lst_h - DIURNAL_PEAK_LST_H) / 24.0).cos();

    let abs_lat = lat_deg.abs();
    let dayw = day_weight(lst_h);

    // Equatorial anomaly: crests either side of the equator, strongest in the
    // afternoon, with a relative trough between them at the magnetic equator.
    // Geographic latitude stands in for magnetic dip latitude here; the two
    // differ by up to ~15 deg, which is a real limitation of this table.
    let u = (abs_lat - ANOMALY_CREST_LAT_DEG) / ANOMALY_CREST_WIDTH_DEG;
    let anomaly = 1.0 + ANOMALY_CREST_GAIN * (-u * u).exp() * dayw;

    // High-latitude trough: a logistic fall-off poleward, at full depth only
    // at night (see POLAR_TROUGH_DAY_FRACTION).
    let t = (abs_lat - POLAR_TROUGH_LAT_DEG) / POLAR_TROUGH_WIDTH_DEG;
    let depth = POLAR_TROUGH_DEPTH * trough_day_weight(dayw);
    let trough = 1.0 - depth / (1.0 + (-t).exp());

    // Seasonal terms, tapering to nothing at the equator.
    let w = (abs_lat / SEASON_FULL_LAT_DEG).min(1.0);
    let seasonal = 1.0
        + w * match season {
            Season::Winter => WINTER_DAY_GAIN * dayw - WINTER_NIGHT_LOSS * (1.0 - dayw),
            Season::Summer => -SUMMER_DAY_LOSS * dayw + SUMMER_NIGHT_GAIN * (1.0 - dayw),
            Season::Equinox => 0.0,
        };

    // Normalise so that the reference latitude at equinox, at the diurnal peak,
    // returns `fof2_from_ssn(ssn)` exactly: the two backends share one anchor.
    let norm = latitude_factor_at_reference();
    let f = reference * diurnal * anomaly * trough * seasonal / norm;
    (f * f + FOF2_FLOOR_MHZ * FOF2_FLOOR_MHZ).sqrt()
}

/// The latitude factor the climatology produces at its own reference point, so
/// the model can divide it out and land exactly on [`fof2_from_ssn`] there.
fn latitude_factor_at_reference() -> f64 {
    let dayw = day_weight(DIURNAL_PEAK_LST_H);
    let u = (REFERENCE_LAT_DEG - ANOMALY_CREST_LAT_DEG) / ANOMALY_CREST_WIDTH_DEG;
    let anomaly = 1.0 + ANOMALY_CREST_GAIN * (-u * u).exp() * dayw;
    let t = (REFERENCE_LAT_DEG - POLAR_TROUGH_LAT_DEG) / POLAR_TROUGH_WIDTH_DEG;
    let trough = 1.0 - POLAR_TROUGH_DEPTH * trough_day_weight(dayw) / (1.0 + (-t).exp());
    anomaly * trough
}

/// Fraction of the trough depth in force at a given "daytime-ness": full at
/// night, `POLAR_TROUGH_DAY_FRACTION` in full daylight.
fn trough_day_weight(dayw: f64) -> f64 {
    POLAR_TROUGH_DAY_FRACTION + (1.0 - POLAR_TROUGH_DAY_FRACTION) * (1.0 - dayw)
}

// --- The bundled grid ------------------------------------------------------

/// Latitude of the first grid row, degrees.
pub const GRID_LAT_MIN_DEG: f64 = -90.0;
/// Latitude spacing between grid rows, degrees.
pub const GRID_LAT_STEP_DEG: f64 = 5.0;
/// Number of latitude rows: -90 to +90 inclusive at 5 deg.
pub const GRID_LAT_ROWS: usize = 37;
/// Local-solar-time spacing between grid columns, hours.
pub const GRID_LST_STEP_H: f64 = 1.0;
/// Number of local-solar-time columns; the axis is periodic, so 24 columns
/// cover 0..24 h with no repeated endpoint.
pub const GRID_LST_COLS: usize = 24;
/// The two solar-activity levels the grid is tabulated at. Two levels
/// interpolated in NmF2 is the CCIR/URSI idiom, kept so that real coefficient
/// data would drop into the same layout.
pub const GRID_SSN_LEVELS: [f64; 2] = [0.0, 100.0];

/// The bundled table, as shipped. See the module docs for its provenance.
const GRID_TSV: &str = include_str!("assets/fof2_grid.tsv");

/// One `(season, ssn level)` page of the grid: foF2 in MHz on the
/// latitude x local-solar-time lattice, row-major by latitude.
type Page = Vec<f64>;

/// The whole bundled table, parsed once.
pub struct Fof2Grid {
    /// Indexed `[season][ssn level]`, seasons ordered winter, equinox, summer.
    pages: [[Page; 2]; 3],
}

fn season_index(s: Season) -> usize {
    match s {
        Season::Winter => 0,
        Season::Equinox => 1,
        Season::Summer => 2,
    }
}

fn season_name(s: Season) -> &'static str {
    match s {
        Season::Winter => "winter",
        Season::Equinox => "equinox",
        Season::Summer => "summer",
    }
}

impl Fof2Grid {
    /// Parse the bundled table.
    ///
    /// # Errors
    /// Returns a description of the first structural problem found. The caller
    /// is expected to fall back to [`Fof2Backend::ConstantSsn`] and say so,
    /// rather than to panic: a broken asset must not take the application down.
    pub fn parse(text: &str) -> Result<Self, String> {
        let empty: Page = Vec::new();
        let mut pages: [[Page; 2]; 3] = [
            [empty.clone(), empty.clone()],
            [empty.clone(), empty.clone()],
            [empty.clone(), empty],
        ];
        for p in &mut pages {
            for q in p.iter_mut() {
                *q = vec![f64::NAN; GRID_LAT_ROWS * GRID_LST_COLS];
            }
        }

        for (lineno, line) in text.lines().enumerate() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let mut f = line.split('\t');
            let at = |what: &str| format!("fof2 grid line {}: missing {what}", lineno + 1);
            let season = f.next().ok_or_else(|| at("season"))?;
            let ssn: f64 = f
                .next()
                .ok_or_else(|| at("ssn"))?
                .parse()
                .map_err(|e| format!("fof2 grid line {}: bad ssn: {e}", lineno + 1))?;
            let lat: f64 = f
                .next()
                .ok_or_else(|| at("lat"))?
                .parse()
                .map_err(|e| format!("fof2 grid line {}: bad lat: {e}", lineno + 1))?;

            let si = [Season::Winter, Season::Equinox, Season::Summer]
                .into_iter()
                .position(|s| season_name(s) == season)
                .ok_or_else(|| format!("fof2 grid line {}: unknown season {season}", lineno + 1))?;
            let ki = GRID_SSN_LEVELS
                .iter()
                .position(|l| (l - ssn).abs() < 1e-9)
                .ok_or_else(|| {
                    format!("fof2 grid line {}: ssn {ssn} is not a tabulated level", lineno + 1)
                })?;
            let row = ((lat - GRID_LAT_MIN_DEG) / GRID_LAT_STEP_DEG).round();
            #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
            let row_i = row as usize;
            if row < 0.0 || row_i >= GRID_LAT_ROWS || (GRID_LAT_MIN_DEG + row * GRID_LAT_STEP_DEG - lat).abs() > 1e-6 {
                return Err(format!(
                    "fof2 grid line {}: latitude {lat} is not on the lattice",
                    lineno + 1
                ));
            }

            let mut n = 0;
            for (col, tok) in f.enumerate() {
                if col >= GRID_LST_COLS {
                    return Err(format!(
                        "fof2 grid line {}: more than {GRID_LST_COLS} columns",
                        lineno + 1
                    ));
                }
                let v: f64 = tok
                    .trim()
                    .parse()
                    .map_err(|e| format!("fof2 grid line {}: bad value: {e}", lineno + 1))?;
                if !(v.is_finite() && v > 0.0) {
                    return Err(format!(
                        "fof2 grid line {}: foF2 must be finite and positive, got {v}",
                        lineno + 1
                    ));
                }
                pages[si][ki][row_i * GRID_LST_COLS + col] = v;
                n += 1;
            }
            if n != GRID_LST_COLS {
                return Err(format!(
                    "fof2 grid line {}: expected {GRID_LST_COLS} columns, got {n}",
                    lineno + 1
                ));
            }
        }

        for (si, page) in pages.iter().enumerate() {
            for (ki, p) in page.iter().enumerate() {
                if let Some(idx) = p.iter().position(|v| v.is_nan()) {
                    return Err(format!(
                        "fof2 grid: season index {si}, ssn level {ki} is missing latitude row {}",
                        idx / GRID_LST_COLS
                    ));
                }
            }
        }
        Ok(Self { pages })
    }

    /// The bundled grid, parsed once per process.
    ///
    /// # Errors
    /// The parse error, verbatim, so the caller can put it in front of the
    /// operator instead of silently substituting a different model.
    pub fn bundled() -> Result<&'static Self, &'static str> {
        static GRID: OnceLock<Result<Fof2Grid, String>> = OnceLock::new();
        match GRID.get_or_init(|| Self::parse(GRID_TSV)) {
            Ok(g) => Ok(g),
            Err(e) => Err(e.as_str()),
        }
    }

    /// Collapse the table to the single latitude x local-time plane this solve
    /// needs, interpolating between the two tabulated solar-activity levels in
    /// NmF2 (i.e. in foF2^2), which is how solar activity enters the physics.
    ///
    /// SSN above the top tabulated level extrapolates along the same line
    /// rather than saturating - the CCIR convention - and is clamped at zero
    /// below, where the linear-in-NmF2 statement would otherwise go negative.
    #[must_use]
    pub fn plane(&self, season: Season, ssn: f64) -> Fof2Plane {
        let [lo_level, hi_level] = GRID_SSN_LEVELS;
        let t = (ssn.max(0.0) - lo_level) / (hi_level - lo_level);
        let page = &self.pages[season_index(season)];
        let values = page[0]
            .iter()
            .zip(&page[1])
            .map(|(lo, hi)| {
                let sq = lo * lo + (hi * hi - lo * lo) * t;
                sq.max(0.0).sqrt()
            })
            .collect();
        Fof2Plane { values }
    }
}

/// One solve's foF2 field: latitude x local solar time, MHz.
pub struct Fof2Plane {
    values: Vec<f64>,
}

/// Catmull-Rom cubic through `p1`/`p2` at parameter `t` in [0, 1], and its
/// derivative with respect to `t`. C1 continuous across cell boundaries, which
/// matters here: a bilinear interpolant's gradient jumps at every cell edge,
/// and the ray equations would integrate straight through those jumps.
fn catmull_rom(p: [f64; 4], t: f64) -> (f64, f64) {
    let (p0, p1, p2, p3) = (p[0], p[1], p[2], p[3]);
    let c0 = p1;
    let c1 = 0.5 * (p2 - p0);
    let c2 = 0.5 * (2.0 * p0 - 5.0 * p1 + 4.0 * p2 - p3);
    let c3 = 0.5 * (-p0 + 3.0 * p1 - 3.0 * p2 + p3);
    (
        c0 + t * (c1 + t * (c2 + t * c3)),
        c1 + t * (2.0 * c2 + 3.0 * t * c3),
    )
}

impl Fof2Plane {
    fn at(&self, row: usize, col: usize) -> f64 {
        self.values[row * GRID_LST_COLS + col]
    }

    /// foF2 [MHz] and its partials `(d/dlat [MHz/deg], d/dLST [MHz/h])` at a
    /// latitude and local solar time.
    ///
    /// Bicubic (tensor-product Catmull-Rom): periodic in local solar time,
    /// edge-clamped in latitude. The partials are the interpolant's own exact
    /// derivatives, not a finite difference of it - the ray equations need the
    /// gradient of the function actually being sampled, or the Hamiltonian
    /// drifts.
    #[must_use]
    pub fn sample(&self, lat_deg: f64, lst_h: f64) -> (f64, f64, f64) {
        let x = (lat_deg.clamp(-90.0, 90.0) - GRID_LAT_MIN_DEG) / GRID_LAT_STEP_DEG;
        let y = lst_h.rem_euclid(24.0) / GRID_LST_STEP_H;
        #[allow(clippy::cast_possible_truncation)]
        let xi = x.floor() as isize;
        #[allow(clippy::cast_possible_truncation)]
        let yi = y.floor() as isize;
        #[allow(clippy::cast_precision_loss)]
        let tx = x - xi as f64;
        #[allow(clippy::cast_precision_loss)]
        let ty = y - yi as f64;

        // Latitude clamps at the poles (there is no row past +-90); local solar
        // time wraps (23 h and 0 h are adjacent).
        #[allow(clippy::cast_possible_wrap)]
        let last_row = GRID_LAT_ROWS as isize - 1;
        let row_of = |k: isize| (xi + k).clamp(0, last_row).unsigned_abs();
        #[allow(clippy::cast_possible_wrap)]
        let cols = GRID_LST_COLS as isize;
        let col_of = |k: isize| (yi + k).rem_euclid(cols).unsigned_abs();

        let mut vals = [0.0_f64; 4];
        let mut dlst = [0.0_f64; 4];
        for (k, (v, d)) in vals.iter_mut().zip(dlst.iter_mut()).enumerate() {
            #[allow(clippy::cast_possible_wrap)]
            let r = row_of(k as isize - 1);
            let row = [
                self.at(r, col_of(-1)),
                self.at(r, col_of(0)),
                self.at(r, col_of(1)),
                self.at(r, col_of(2)),
            ];
            let (value, deriv) = catmull_rom(row, ty);
            *v = value;
            *d = deriv;
        }
        let (f, df_dx) = catmull_rom(vals, tx);
        let (df_dy, _) = catmull_rom(dlst, tx);
        (
            f,
            df_dx / GRID_LAT_STEP_DEG,
            df_dy / GRID_LST_STEP_H,
        )
    }
}

// --- Peak-density sources --------------------------------------------------

/// Radians-per-degree chain factors from the grid's axes to the engine's
/// coordinates. `lat = 90 - theta` in degrees, so `dlat/dtheta = -180/pi`;
/// `LST = utc + lon/15` in hours with `lon` in degrees, so
/// `dLST/dphi = (180/pi)/15 = 12/pi`.
const DLAT_DEG_DTHETA: f64 = -180.0 / PI;
const DLST_H_DPHI: f64 = 12.0 / PI;

/// Peak density of the F2 layer from the gridded climatology.
pub struct GriddedF2Peak {
    plane: Fof2Plane,
    utc_hours: f64,
}

impl GriddedF2Peak {
    #[must_use]
    pub fn new(plane: Fof2Plane, utc_hours: f64) -> Self {
        Self { plane, utc_hours }
    }

    /// foF2 [MHz] at a geographic position, for display and for the harness.
    #[must_use]
    pub fn fof2_at(&self, lat_deg: f64, lon_deg: f64) -> f64 {
        let lst = (self.utc_hours + lon_deg / 15.0).rem_euclid(24.0);
        self.plane.sample(lat_deg, lst).0
    }
}

/// NmF2 and its partials from foF2 and the interpolant's partials.
/// `Nm = K f^2`, so `dNm/dx = 2 K f (df/dx) = (2 Nm / f) (df/dx)`.
fn peak_from_fof2(f_mhz: f64, df_dlat_deg: f64, df_dlst_h: f64) -> PeakSample {
    let nm = density_at_critical_frequency(Hertz::new(f_mhz * 1e6)).get();
    // A non-positive or NaN foF2 has no gradient to report; tested this way
    // round so that NaN takes the same branch as zero rather than slipping
    // through a negated comparison.
    if !f_mhz.is_finite() || f_mhz <= 0.0 {
        return PeakSample::uniform(0.0);
    }
    let k = 2.0 * nm / f_mhz;
    PeakSample {
        nm,
        d_nm: [
            k * df_dlat_deg * DLAT_DEG_DTHETA,
            k * df_dlst_h * DLST_H_DPHI,
        ],
    }
}

impl PeakDensitySource for GriddedF2Peak {
    fn peak(&self, colat: f64, lon: f64) -> PeakSample {
        let lat_deg = 90.0 - colat.to_degrees();
        // LST is linear in longitude, so no wrapping is needed for the
        // derivative; `sample` wraps the value itself.
        let lst = self.utc_hours + lon * DLST_H_DPHI;
        let (f, df_dlat, df_dlst) = self.plane.sample(lat_deg, lst);
        peak_from_fof2(f, df_dlat, df_dlst)
    }
}

// --- E layer ---------------------------------------------------------------

/// Overhead-sun foE at zero sunspot number, MHz. ORDER-OF-MAGNITUDE ANCHOR:
/// noon midlatitude foE sits in the 3-4 MHz range across the solar cycle, and
/// 3.30 MHz at SSN 0 puts the model in that range. Not a fitted coefficient.
pub const FOE_OVERHEAD_QUIET_MHZ: f64 = 3.30;
/// Solar-activity scaling of foE. The standard statement is
/// `foE^4 proportional to (1 + 0.0094 R) cos(chi)`; only the `(1 + 0.0094 R)`
/// factor is applied here, because the `cos(chi)` half is produced by the
/// layer itself - an alpha-Chapman layer on the grazing function realises a
/// peak of `Nm Ch^(-1/2)`, i.e. `foE` proportional to `(cos chi)^(1/4)` in the
/// plane-parallel regime, which is exactly that law. Applying it twice would
/// double-count it.
pub const FOE_SOLAR_COEFF: f64 = 0.009_4;

/// Overhead-sun (chi = 0) foE [MHz] at a sunspot number.
#[must_use]
pub fn foe_overhead(ssn: f64) -> f64 {
    FOE_OVERHEAD_QUIET_MHZ * (1.0 + FOE_SOLAR_COEFF * ssn.max(0.0)).powf(0.25)
}

/// Overhead-sun peak density of the E layer, m^-3.
#[must_use]
pub fn e_layer_peak_ne(ssn: f64) -> f64 {
    density_at_critical_frequency(Hertz::new(foe_overhead(ssn) * 1e6)).get()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// foF2(SSN) hits its calibration anchors, rises monotonically with solar
    /// activity, and clamps negative SSN rather than producing NaN.
    #[test]
    fn fof2_from_ssn_monotonic_and_anchored() {
        assert!(
            (fof2_from_ssn(0.0) - 4.5).abs() < 0.02,
            "{}",
            fof2_from_ssn(0.0)
        );
        assert!(
            (fof2_from_ssn(150.0) - 10.0).abs() < 0.05,
            "{}",
            fof2_from_ssn(150.0)
        );
        let mut prev = fof2_from_ssn(0.0);
        for s in 1..=300 {
            let v = fof2_from_ssn(f64::from(s));
            assert!(v > prev, "not monotonic at SSN {s}: {v} <= {prev}");
            prev = v;
        }
        // Negative SSN is clamped to the SSN = 0 value (never NaN).
        assert_eq!(fof2_from_ssn(-40.0), fof2_from_ssn(0.0));
    }

    /// The two backends share one anchor: at the reference latitude, at
    /// equinox, at the diurnal peak, the climatology must return exactly what
    /// the scalar model returns. Without this, switching backends would move
    /// the absolute level as well as adding structure, and no comparison
    /// between them would mean anything.
    #[test]
    fn climatology_reduces_to_the_scalar_anchor_at_its_reference_point() {
        for ssn in [0.0, 30.0, 70.0, 150.0, 250.0] {
            let want = fof2_from_ssn(ssn);
            let got = climatology_fof2(
                REFERENCE_LAT_DEG,
                DIURNAL_PEAK_LST_H,
                Season::Equinox,
                ssn,
            );
            // The soft floor lifts the value very slightly; that is the only
            // permitted difference, and it is bounded by it.
            let floored = (want * want + FOF2_FLOOR_MHZ * FOF2_FLOOR_MHZ).sqrt();
            assert!(
                (got - floored).abs() < 1e-9,
                "SSN {ssn}: climatology {got} vs anchor {floored}"
            );
        }
    }

    /// The behaviours the climatology claims, each checked as a trend rather
    /// than against an absolute value (the anchors do not support absolutes).
    #[test]
    fn climatology_trends_are_as_documented() {
        let ssn = 70.0;

        // Afternoon exceeds pre-dawn everywhere, by roughly the documented ratio.
        for lat in [-60.0, -20.0, 0.0, 35.0, 70.0] {
            let day = climatology_fof2(lat, 14.0, Season::Equinox, ssn);
            let night = climatology_fof2(lat, 4.0, Season::Equinox, ssn);
            assert!(day > night, "lat {lat}: day {day} <= night {night}");
        }

        // Equatorial anomaly: a crest near +-16 deg standing above both the
        // magnetic equator and the midlatitudes, in the afternoon.
        let crest = climatology_fof2(ANOMALY_CREST_LAT_DEG, 15.0, Season::Equinox, ssn);
        let equator = climatology_fof2(0.0, 15.0, Season::Equinox, ssn);
        let midlat = climatology_fof2(45.0, 15.0, Season::Equinox, ssn);
        assert!(crest > equator, "crest {crest} <= equator {equator}");
        assert!(crest > midlat, "crest {crest} <= midlat {midlat}");
        // ...and it is a daytime feature: at night the crest all but vanishes.
        let crest_night = climatology_fof2(ANOMALY_CREST_LAT_DEG, 3.0, Season::Equinox, ssn);
        let equator_night = climatology_fof2(0.0, 3.0, Season::Equinox, ssn);
        assert!(
            (crest_night - equator_night).abs() < 0.25 * (crest - equator),
            "the anomaly should be a daytime feature"
        );

        // High-latitude trough: 75 deg sits below 45 deg at the same hour, and
        // it is DEEPER AT NIGHT than in daylight - the main ionospheric trough
        // is predominantly a night-time feature (POLAR_TROUGH_DAY_FRACTION).
        let day_ratio = climatology_fof2(75.0, 14.0, Season::Equinox, ssn)
            / climatology_fof2(45.0, 14.0, Season::Equinox, ssn);
        let night_ratio = climatology_fof2(75.0, 2.0, Season::Equinox, ssn)
            / climatology_fof2(45.0, 2.0, Season::Equinox, ssn);
        assert!(day_ratio < 1.0, "no daytime trough at all: {day_ratio}");
        assert!(night_ratio < 0.8, "night trough too shallow: {night_ratio}");
        assert!(
            night_ratio < day_ratio,
            "the trough must be deeper at night ({night_ratio}) than by day ({day_ratio})"
        );

        // Winter anomaly: midlatitude winter DAY beats summer day; the sign
        // reverses at night. This is the behaviour a pure zenith-angle model
        // cannot produce, and the reason F2 does not use one.
        let w_day = climatology_fof2(50.0, 13.0, Season::Winter, ssn);
        let s_day = climatology_fof2(50.0, 13.0, Season::Summer, ssn);
        assert!(w_day > s_day, "winter day {w_day} <= summer day {s_day}");
        let w_night = climatology_fof2(50.0, 2.0, Season::Winter, ssn);
        let s_night = climatology_fof2(50.0, 2.0, Season::Summer, ssn);
        assert!(
            s_night > w_night,
            "summer night {s_night} <= winter night {w_night}"
        );

        // The seasonal terms taper out at the equator.
        let eq_w = climatology_fof2(0.0, 13.0, Season::Winter, ssn);
        let eq_s = climatology_fof2(0.0, 13.0, Season::Summer, ssn);
        assert!((eq_w - eq_s).abs() < 1e-9);

        // The floor holds: foF2 never collapses, even at the worst combination.
        for lat in [-88.0, -45.0, 0.0, 45.0, 88.0] {
            for lst in [0.0, 3.0, 5.0] {
                let f = climatology_fof2(lat, lst, Season::Winter, 0.0);
                assert!(f >= FOF2_FLOOR_MHZ, "lat {lat} lst {lst}: foF2 {f}");
            }
        }
    }

    /// The bundled asset parses, covers the whole lattice, and holds the values
    /// `climatology_fof2` produces - i.e. the shipped data really is what the
    /// module says it is, and has not drifted from the generator.
    #[test]
    fn bundled_grid_matches_its_generator() {
        let grid = Fof2Grid::bundled().expect("bundled fof2 grid parses");
        for season in [Season::Winter, Season::Equinox, Season::Summer] {
            for (ki, level) in GRID_SSN_LEVELS.into_iter().enumerate() {
                let page = &grid.pages[season_index(season)][ki];
                for row in 0..GRID_LAT_ROWS {
                    #[allow(clippy::cast_precision_loss)]
                    let lat = GRID_LAT_MIN_DEG + row as f64 * GRID_LAT_STEP_DEG;
                    for col in 0..GRID_LST_COLS {
                        #[allow(clippy::cast_precision_loss)]
                        let lst = col as f64 * GRID_LST_STEP_H;
                        let want = climatology_fof2(lat, lst, season, level);
                        let got = page[row * GRID_LST_COLS + col];
                        assert!(
                            (got - want).abs() < 5e-4,
                            "{}/{level} at lat {lat}, lst {lst}: grid {got} vs generator {want}",
                            season_name(season)
                        );
                    }
                }
            }
        }
    }

    /// The interpolant passes through the tabulated values at the nodes, and
    /// its analytic partials match central differences of itself everywhere
    /// else. The second half is the one that matters: the ray equations use
    /// these partials, and a gradient that does not match its own field is what
    /// drives Hamiltonian drift.
    #[test]
    fn plane_interpolates_nodes_and_its_partials_are_exact() {
        let grid = Fof2Grid::bundled().expect("grid");
        let plane = grid.plane(Season::Summer, 70.0);

        for row in 0..GRID_LAT_ROWS {
            #[allow(clippy::cast_precision_loss)]
            let lat = GRID_LAT_MIN_DEG + row as f64 * GRID_LAT_STEP_DEG;
            for col in 0..GRID_LST_COLS {
                #[allow(clippy::cast_precision_loss)]
                let lst = col as f64 * GRID_LST_STEP_H;
                let (f, _, _) = plane.sample(lat, lst);
                assert!(
                    (f - plane.at(row, col)).abs() < 1e-9,
                    "node ({lat}, {lst}): {f} vs {}",
                    plane.at(row, col)
                );
            }
        }

        for &lat in &[-71.3_f64, -18.0, 0.7, 22.4, 47.9, 63.2, 88.0] {
            for &lst in &[0.4_f64, 3.7, 9.25, 13.1, 17.8, 23.6] {
                let (_, dlat, dlst) = plane.sample(lat, lst);
                let h = 1e-5;
                let fd_lat =
                    (plane.sample(lat + h, lst).0 - plane.sample(lat - h, lst).0) / (2.0 * h);
                let fd_lst =
                    (plane.sample(lat, lst + h).0 - plane.sample(lat, lst - h).0) / (2.0 * h);
                assert!(
                    (dlat - fd_lat).abs() < 1e-6 * fd_lat.abs().max(1.0),
                    "d/dlat at ({lat}, {lst}): {dlat} vs {fd_lat}"
                );
                assert!(
                    (dlst - fd_lst).abs() < 1e-6 * fd_lst.abs().max(1.0),
                    "d/dLST at ({lat}, {lst}): {dlst} vs {fd_lst}"
                );
            }
        }
    }

    /// Local solar time is periodic: 24 h and 0 h are the same point, value and
    /// gradient. A seam here would show up as a spurious refraction wall at one
    /// meridian.
    #[test]
    fn plane_is_periodic_in_local_time() {
        let plane = Fof2Grid::bundled().unwrap().plane(Season::Equinox, 40.0);
        for lat in [-55.0, 0.0, 33.0] {
            let a = plane.sample(lat, 0.0);
            let b = plane.sample(lat, 24.0);
            assert!((a.0 - b.0).abs() < 1e-12, "value seam at lat {lat}");
            assert!((a.2 - b.2).abs() < 1e-12, "gradient seam at lat {lat}");
        }
    }

    /// The solar-activity interpolation is linear in NmF2 (i.e. in foF2^2),
    /// hits both tabulated levels exactly, and extrapolates above the top one.
    #[test]
    fn plane_interpolates_solar_activity_in_density() {
        let grid = Fof2Grid::bundled().unwrap();
        let (lat, lst) = (37.5, 11.0);
        let lo = grid.plane(Season::Equinox, 0.0).sample(lat, lst).0;
        let hi = grid.plane(Season::Equinox, 100.0).sample(lat, lst).0;
        let mid = grid.plane(Season::Equinox, 50.0).sample(lat, lst).0;
        let want = (0.5 * (lo * lo + hi * hi)).sqrt();
        // Not exact, and not expected to be: the solar blend is linear in
        // foF2^2 while the bicubic runs on foF2, and the two do not commute
        // through the square root. The residual is ~1e-7 relative - orders
        // below anything physical, and far below the ~1e-2 a wrong blend
        // (linear in foF2, or in the wrong page) would produce.
        assert!(
            (mid - want).abs() < 1e-4 * want,
            "{mid} vs {want} (relative {:.2e})",
            (mid - want).abs() / want
        );
        // Above the top level it keeps going rather than saturating.
        let high = grid.plane(Season::Equinox, 200.0).sample(lat, lst).0;
        assert!(high > hi, "SSN 200 {high} should exceed SSN 100 {hi}");
    }

    /// The F2 peak source's partials, in ENGINE coordinates, against central
    /// differences of its own Ne. This is the check that the two chain-rule
    /// factors (lat from colatitude, LST from longitude) carry the right signs;
    /// a flipped sign here is invisible in the density and fatal in the tracer.
    #[test]
    fn gridded_peak_partials_match_fd() {
        let plane = Fof2Grid::bundled().unwrap().plane(Season::Summer, 90.0);
        let src = GriddedF2Peak::new(plane, 6.0);
        for (colat, lon) in [
            (0.9_f64, 0.3_f64),
            (1.6, -2.2),
            (2.4, 1.1),
            (0.35, 3.0),
            (2.8, -0.4),
        ] {
            let s = src.peak(colat, lon);
            let h = 1e-6;
            let fd_theta =
                (src.peak(colat + h, lon).nm - src.peak(colat - h, lon).nm) / (2.0 * h);
            let fd_phi = (src.peak(colat, lon + h).nm - src.peak(colat, lon - h).nm) / (2.0 * h);
            assert!(
                (s.d_nm[0] - fd_theta).abs() < 1e-6 * fd_theta.abs().max(1e-3 * s.nm),
                "dtheta at ({colat}, {lon}): {} vs {fd_theta}",
                s.d_nm[0]
            );
            assert!(
                (s.d_nm[1] - fd_phi).abs() < 1e-6 * fd_phi.abs().max(1e-3 * s.nm),
                "dphi at ({colat}, {lon}): {} vs {fd_phi}",
                s.d_nm[1]
            );
        }
    }

    /// Sign check with a physical meaning, independent of the finite-difference
    /// test above: at a longitude where local time is climbing towards the
    /// afternoon peak, moving east (increasing phi, later local time) must
    /// INCREASE NmF2. If the 12/pi factor had the wrong sign this would fail
    /// while the FD test still passed, because FD would agree with the error.
    #[test]
    fn moving_towards_local_afternoon_raises_nmf2() {
        let plane = Fof2Grid::bundled().unwrap().plane(Season::Equinox, 70.0);
        // UTC 0, so local solar time equals longitude/15 h. At lon 0 the local
        // time is midnight; at lon 150 deg east it is 10 h, still climbing to
        // the 14 h peak.
        let src = GriddedF2Peak::new(plane, 0.0);
        let colat = std::f64::consts::FRAC_PI_2 - 45.0_f64.to_radians();
        let lon = 150.0_f64.to_radians();
        assert!(
            src.peak(colat, lon).d_nm[1] > 0.0,
            "eastward towards local afternoon must raise NmF2"
        );
        // And north of the equatorial crest, moving towards the equator
        // (increasing colatitude in the northern hemisphere) must raise it too.
        let src2 = GriddedF2Peak::new(Fof2Grid::bundled().unwrap().plane(Season::Equinox, 70.0), 0.0);
        let colat_35n = std::f64::consts::FRAC_PI_2 - 35.0_f64.to_radians();
        // Local afternoon at lon 150 deg east: the crest is present.
        assert!(
            src2.peak(colat_35n, 45.0_f64.to_radians()).d_nm[0] > 0.0,
            "moving equatorward towards the anomaly crest must raise NmF2"
        );
    }

    /// foE follows the standard solar-activity scaling and lands in the
    /// documented 3-4 MHz band across a realistic solar cycle.
    #[test]
    fn foe_is_in_range_and_rises_with_solar_activity() {
        assert!((foe_overhead(0.0) - FOE_OVERHEAD_QUIET_MHZ).abs() < 1e-12);
        let mut prev = foe_overhead(0.0);
        for ssn in 1..=250 {
            let v = foe_overhead(f64::from(ssn));
            assert!(v > prev);
            prev = v;
        }
        assert!(
            (3.0..4.5).contains(&foe_overhead(150.0)),
            "foE at SSN 150 = {}",
            foe_overhead(150.0)
        );
        // Nm follows foE^2, so the round trip must close.
        let ne = e_layer_peak_ne(70.0);
        let back = skipzone::density::critical_frequency(skipzone::units::PerCubicMeter::new(ne));
        assert!((back.get() / 1e6 - foe_overhead(70.0)).abs() < 1e-6);
    }
}
